# Generated by Django 4.0.6 on 2022-07-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Name of the student', max_length=30)),
                ('last_name', models.CharField(help_text='Last name of the student', max_length=30)),
                ('birth_date', models.DateField(help_text='Birth date of the student')),
                ('GPA', models.FloatField(help_text='GPA of the student')),
            ],
        ),
    ]
