# Generated by Django 4.0.6 on 2022-07-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=512)),
                ('lname', models.CharField(max_length=512)),
                ('dob', models.DateField()),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
